name: deploy lambda function
on:
  push:
    branches:
      - main

jobs:
  umedi-appointment-api:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to repo
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: compress codes
        run: zip -r9 umedi-subtask-api.zip *

      - name: deploy lambda function
        run: aws lambda update-function-code --function-name=umedi-subtask-api --zip-file=fileb://umedi-subtask-api.zip
      # - name: Deploy lambda function
      #   run: sls deploy